apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quotes-api-ingress
  labels:
    app: quotes-api
spec:
  ingressClassName: nginx
  rules:
    - host: quotes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quotes-api
                port:
                  number: 80

