apiVersion: v1
kind: Service
metadata:
  name: quotes-api
  labels:
    app: quotes-api
spec:
  type: ClusterIP
  selector:
    app: quotes-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
